package business.models;

public enum EstadoPedido {
    PEDIDO_VALIDO,
    PEDIDO_SIN_PRODUCTOS,
    PRODUCTO_CON_EXISTENCIA_INSUFICIENTE,
    PEDIDO_CON_DESCUENTO,
    PEDIDO_SIN_DESCUENTO,
    PEDIDO_MARCADO_COMO_FRAUDE,
    PEDIDO_CONFIRMADO,
    PEDIDO_PROCESADO,
}
